"""
RULE_MEDIA_WEIGHTS.py  —  AUTO-GENERATED, but meant to be reviewed & edited
=========================================================================
For every tagged rule id the splitter can stamp on a line, this maps:

    <rule id> -> { 'description': <what the splitter spotted>,
                   'media_type_probabilities': { <shot template>: affinity } }

The keys are SHOT TEMPLATE names from SPLIT_AND_LABEL_CONFIG.SHOT_TEMPLATES
(NOT the renderer's legacy MediaType strings — the legacy bridge in the
config translates at emit time).

The affinities are INDEPENDENT scores in [0,1] ('how well does this shot
template suit a line the splitter cut for THIS reason'), NOT a
distribution — they do not sum to 1.  They matter ONLY for TIER 3 of the
decision ladder in SPLIT_AND_LABEL.py: tier-0 gates and tier-1 locks run
first and are deterministic; these weights just shape the sampling for
lines that nothing locked.

Descriptions are mirrored from sentence_splitter.RULE_DESCRIPTIONS so you
can review the number -> meaning -> shot-template linking in one place.
Regenerate with:  python3 gen_rule_media_weights.py > RULE_MEDIA_WEIGHTS.py
"""

RULE_MEDIA_WEIGHTS = {
    # the line ends with . ! ? ; or : — e.g. 'The dog jumped.' | 'The man ra
    1: {
        'new__stock': 0.55,
        'new__object': 0.2,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.495,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.275,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a dash breaks the line — e.g. 'it was huge —' | 'completely massive'
    2: {
        'new__stock': 0.45,
        'new__object': 0.25,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.405,
        'editprev__ai_edit': 0.15,
        'new__stock_on_board': 0.225,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.15,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # the line ends on a '...' or '…' — e.g. 'and then...' | 'silence'
    3: {
        'new__stock': 0.3,
        'new__object': 0.15,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.35,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.35,
        'editprev__hold': 0.3,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # the dramatic phrase right before a '...' gets its own line — e.g. 'the
    4: {
        'new__stock': 0.35,
        'new__object': 0.6,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.315,
        'editprev__ai_edit': 0.2,
        'new__stock_on_board': 0.175,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.2,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a phrase in quotation marks gets its own line — e.g. she yelled | 'sto
    5: {
        'new__stock': 0.2,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.18,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.1,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.35,
        'editprev__draw': 0.6,
        'editprev__caption': 0.6,
    },
    # an aside in (brackets) gets its own line — e.g. 'the house' | '(built 
    6: {
        'new__stock': 0.25,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.225,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.125,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.3,
        'editprev__draw': 0.4,
        'editprev__caption': 0.4,
    },
    # a scene-setting opener that ends in a comma — e.g. 'In the morning,' |
    7: {
        'new__stock': 0.4,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.12,
        'new__typography': 0.01,
        'new__ai_stock': 0.36,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.2,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.25,
        'editprev__draw': 0.15,
        'editprev__caption': 0.15,
    },
    # a comma that separates two clauses or list items — e.g. 'she ran,' | '
    8: {
        'new__stock': 0.55,
        'new__object': 0.18,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.495,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.275,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a comma that introduces a 'who / which / that...' description — e.g. '
    9: {
        'new__stock': 0.3,
        'new__object': 0.12,
        'new__wikipedia': 0.22,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.165,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.5,
        'editprev__caption': 0.5,
    },
    # a joining word like 'when', 'because', 'which' or 'that' starts a new 
    10: {
        'new__stock': 0.3,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.2,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.2,
        'editprev__hold': 0.4,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a 'but', 'or', 'so' or 'yet' after a long first part — e.g. 'we tried 
    11: {
        'new__stock': 0.3,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.2,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.2,
        'editprev__hold': 0.4,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # one complete action has finished and the next begins — e.g. 'the baker
    12: {
        'new__stock': 0.5,
        'new__object': 0.25,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.45,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.25,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a very long wind-up finally reaches its main verb (a safety net for ru
    13: {
        'new__stock': 0.35,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.315,
        'editprev__ai_edit': 0.15,
        'new__stock_on_board': 0.175,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.15,
        'editprev__hold': 0.4,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a long 'in / on / at / with...' phrase — e.g. 'she hid' | 'beneath the
    14: {
        'new__stock': 0.42,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.12,
        'new__typography': 0.01,
        'new__ai_stock': 0.378,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.21,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.18,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a run of things listed with no verb between them — e.g. 'ribs,' | 'ver
    15: {
        'new__stock': 0.3,
        'new__object': 0.2,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # another 'thing, the thing, the thing' list that the usual list-finder 
    16: {
        'new__stock': 0.3,
        'new__object': 0.2,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a wrap-up word like 'all', 'both', 'each' or 'every' right after a lis
    17: {
        'new__stock': 0.3,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.25,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.25,
        'editprev__hold': 0.35,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a name worth a dramatic reveal — a person, place, date or amount — e.g
    18: {
        'new__stock': 0.35,
        'new__object': 0.35,
        'new__wikipedia': 0.65,
        'new__map': 0.3,
        'new__typography': 0.01,
        'new__ai_stock': 0.315,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.175,
        'new__wikipedia_on_board': 0.488,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # an amount of money gets its own line — e.g. 'it costs' | '$800,000'
    19: {
        'new__stock': 0.4,
        'new__object': 0.6,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.36,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.2,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a short command on its own — e.g. 'Stop.' | 'Look around.'
    20: {
        'new__stock': 0.3,
        'new__object': 0.2,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.3,
        'editprev__draw': 0.45,
        'editprev__caption': 0.45,
    },
    # an 'and' or 'or' joining two complete sentences — e.g. 'she sang' | 'a
    21: {
        'new__stock': 0.35,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.315,
        'editprev__ai_edit': 0.15,
        'new__stock_on_board': 0.175,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.15,
        'editprev__hold': 0.35,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a describing word revealed in the middle of a sentence — e.g. 'the wat
    23: {
        'new__stock': 0.28,
        'new__object': 0.25,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.252,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.14,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.55,
        'editprev__caption': 0.55,
    },
    # a sentence ending on a number or amount — e.g. 'the whales vanished' |
    24: {
        'new__stock': 0.42,
        'new__object': 0.35,
        'new__wikipedia': 0.12,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.378,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.21,
        'new__wikipedia_on_board': 0.09,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # an extra comma-list pattern the basic comma rule misses — e.g. 'soaked
    25: {
        'new__stock': 0.3,
        'new__object': 0.2,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a long 'if / when / because...' opener that ends in a comma — e.g. 'if
    26: {
        'new__stock': 0.3,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.2,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.2,
        'editprev__hold': 0.42,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a sentence ending on a pair of describing words — e.g. 'the place felt
    27: {
        'new__stock': 0.28,
        'new__object': 0.25,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.252,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.14,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.52,
        'editprev__caption': 0.52,
    },
    # a chunky 'of / in / with...' phrase stuffed with nouns and no verb — e
    28: {
        'new__stock': 0.4,
        'new__object': 0.28,
        'new__wikipedia': 0.15,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.36,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.2,
        'new__wikipedia_on_board': 0.112,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # an '-ing' or '-ed' word that introduces what comes next — e.g. 'reveal
    29: {
        'new__stock': 0.3,
        'new__object': 0.35,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.38,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.38,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # after a place or name, the 'in / on / at...' that says WHERE splits of
    30: {
        'new__stock': 0.3,
        'new__object': 0.12,
        'new__wikipedia': 0.15,
        'new__map': 0.78,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.112,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a comma after a long, meaty clause — e.g. 'after searching the whole h
    31: {
        'new__stock': 0.3,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.15,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.15,
        'editprev__hold': 0.4,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a 'to do something' inside a long sentence — e.g. 'they travelled for 
    32: {
        'new__stock': 0.42,
        'new__object': 0.2,
        'new__wikipedia': 0.08,
        'new__map': 0.1,
        'new__typography': 0.01,
        'new__ai_stock': 0.378,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.21,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a sentence ending on an 'of ...' phrase — e.g. 'one of the driest' | '
    33: {
        'new__stock': 0.44,
        'new__object': 0.3,
        'new__wikipedia': 0.08,
        'new__map': 0.1,
        'new__typography': 0.01,
        'new__ai_stock': 0.396,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.22,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # an 'is / was ...-ing' action in progress — e.g. 'the crowd was' | 'slo
    34: {
        'new__stock': 0.3,
        'new__object': 0.2,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.32,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.32,
        'editprev__hold': 0.35,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # an 'is / looks / feels...' followed by the thing it describes — e.g. '
    35: {
        'new__stock': 0.3,
        'new__object': 0.3,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.48,
        'editprev__caption': 0.48,
    },
    # an 'it / them + -ing/-ed' description after a small word like 'of' — e
    36: {
        'new__stock': 0.25,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.225,
        'editprev__ai_edit': 0.22,
        'new__stock_on_board': 0.125,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.22,
        'editprev__hold': 0.4,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a sentence ending on a describing word plus an 'in / on / for...' phra
    37: {
        'new__stock': 0.38,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.12,
        'new__typography': 0.01,
        'new__ai_stock': 0.342,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.19,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.22,
        'editprev__caption': 0.22,
    },
    # a two-word verb (like 'set up', 'sped past') and the thing it acts on 
    38: {
        'new__stock': 0.4,
        'new__object': 0.52,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.36,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.2,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # the thing after a preposition gets its own line — e.g. 'shapes appeare
    39: {
        'new__stock': 0.42,
        'new__object': 0.25,
        'new__wikipedia': 0.08,
        'new__map': 0.12,
        'new__typography': 0.01,
        'new__ai_stock': 0.378,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.21,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a scene-change word like 'then', 'later' or 'suddenly' — e.g. 'they wa
    40: {
        'new__stock': 0.3,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.38,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.38,
        'editprev__zoom': 0.22,
        'editprev__hold': 0.3,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a joining word like 'as', 'while' or 'if' left hanging as a cliffhange
    41: {
        'new__stock': 0.45,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.405,
        'editprev__ai_edit': 0.35,
        'new__stock_on_board': 0.225,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.35,
        'editprev__hold': 0.4,
        'editprev__draw': 0.18,
        'editprev__caption': 0.18,
    },
    # 'X is / looks / becomes Y' — split to reveal the Y — e.g. 'the desert 
    42: {
        'new__stock': 0.4,
        'new__object': 0.52,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.36,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.2,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.2,
        'editprev__caption': 0.2,
    },
    # 'X has / owns / contains Y' — split to reveal the Y — e.g. 'the valley
    43: {
        'new__stock': 0.35,
        'new__object': 0.55,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.315,
        'editprev__ai_edit': 0.28,
        'new__stock_on_board': 0.175,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.28,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # 'X made / built / created Y' — split to reveal the Y — e.g. 'the river
    44: {
        'new__stock': 0.4,
        'new__object': 0.52,
        'new__wikipedia': 0.08,
        'new__map': 0.15,
        'new__typography': 0.01,
        'new__ai_stock': 0.36,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.2,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # 'X saw / found / knew Y' — split to reveal the Y — e.g. 'scientists di
    45: {
        'new__stock': 0.4,
        'new__object': 0.52,
        'new__wikipedia': 0.18,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.36,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.2,
        'new__wikipedia_on_board': 0.135,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # 'X moves through / into / across Y' — split to reveal the place — e.g.
    46: {
        'new__stock': 0.35,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.58,
        'new__typography': 0.01,
        'new__ai_stock': 0.315,
        'editprev__ai_edit': 0.18,
        'new__stock_on_board': 0.175,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.18,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # 'so / such / more ... that / than ...' — split right before the payoff
    47: {
        'new__stock': 0.3,
        'new__object': 0.25,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.2,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.2,
        'editprev__hold': 0.35,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # 'X means / equals / stands for Y' — split to reveal the meaning — e.g.
    48: {
        'new__stock': 0.3,
        'new__object': 0.3,
        'new__wikipedia': 0.52,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.39,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.2,
        'editprev__caption': 0.2,
    },
    # an 'and' / 'or' sitting between two picture-able things — e.g. 'dunes'
    49: {
        'new__stock': 0.35,
        'new__object': 0.3,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.315,
        'editprev__ai_edit': 0.26,
        'new__stock_on_board': 0.175,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.26,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # after a title-name like 'Alaric the Goth', split before the verb — e.g
    50: {
        'new__stock': 0.3,
        'new__object': 0.3,
        'new__wikipedia': 0.72,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.54,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # the first item of a list gets its own line too — e.g. 'dunes,' | 'heat
    51: {
        'new__stock': 0.3,
        'new__object': 0.2,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a sentence ending on a label that explains the thing just named — e.g.
    52: {
        'new__stock': 0.35,
        'new__object': 0.35,
        'new__wikipedia': 0.22,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.315,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.175,
        'new__wikipedia_on_board': 0.165,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.32,
        'editprev__caption': 0.32,
    },
    # a number or date right at the start of a sentence — e.g. 'In 1946,' | 
    53: {
        'new__stock': 0.42,
        'new__object': 0.25,
        'new__wikipedia': 0.08,
        'new__map': 0.15,
        'new__typography': 0.01,
        'new__ai_stock': 0.378,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.21,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.2,
        'editprev__caption': 0.2,
    },
    # the sentence ends on a describing word or phrase that paints the pictu
    54: {
        'new__stock': 0.28,
        'new__object': 0.25,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.252,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.14,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.52,
        'editprev__caption': 0.52,
    },
    # a roughly-this-much amount like 'nearly 500' or 'about two miles' — e.
    55: {
        'new__stock': 0.44,
        'new__object': 0.3,
        'new__wikipedia': 0.08,
        'new__map': 0.08,
        'new__typography': 0.01,
        'new__ai_stock': 0.396,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.22,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a comparison with 'like' / 'as if' / 'resembling' — cut to the compare
    56: {
        'new__stock': 0.45,
        'new__object': 0.45,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.405,
        'editprev__ai_edit': 0.15,
        'new__stock_on_board': 0.225,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.15,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # an exception reveal with 'except' or 'apart from' — cut to the one thi
    57: {
        'new__stock': 0.35,
        'new__object': 0.25,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.315,
        'editprev__ai_edit': 0.4,
        'new__stock_on_board': 0.175,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.4,
        'editprev__hold': 0.08,
        'editprev__draw': 0.3,
        'editprev__caption': 0.3,
    },
    # a retention hook like 'here's the thing' or 'which brings us to' gets 
    58: {
        'new__stock': 0.25,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.225,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.125,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.35,
        'editprev__draw': 0.55,
        'editprev__caption': 0.55,
    },
    # the doer in a passive 'by ...' phrase — cut to who or what did it — e.
    59: {
        'new__stock': 0.45,
        'new__object': 0.25,
        'new__wikipedia': 0.3,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.405,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.225,
        'new__wikipedia_on_board': 0.225,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a sound word like 'boom' or 'crash' stands alone as an SFX sync point 
    60: {
        'new__stock': 0.2,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.18,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.1,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.35,
        'editprev__draw': 0.6,
        'editprev__caption': 0.6,
    },
    # a tiny leftover bit (like 'and' or 'the') is attached to the line BEFO
    1000: {
        'new__stock': 0.3,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.2,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.2,
        'editprev__hold': 0.4,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a tiny leftover bit is attached to the line AFTER it, where it belongs
    1001: {
        'new__stock': 0.3,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.2,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.2,
        'editprev__hold': 0.4,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a lonely piece of punctuation ('...', a dash, a stray quote) is stuck 
    1002: {
        'new__stock': 0.35,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.315,
        'editprev__ai_edit': 0.15,
        'new__stock_on_board': 0.175,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.15,
        'editprev__hold': 0.35,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a lone noun is reunited with the 'that / which...' description that fo
    1003: {
        'new__stock': 0.3,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.3,
        'editprev__draw': 0.35,
        'editprev__caption': 0.35,
    },
    # a short scrap is joined back to the 'to / of / with...' word it comple
    1004: {
        'new__stock': 0.35,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.315,
        'editprev__ai_edit': 0.15,
        'new__stock_on_board': 0.175,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.15,
        'editprev__hold': 0.35,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a lone '-ing / -ed' verb is reunited with the thing it acts on — e.g. 
    1005: {
        'new__stock': 0.35,
        'new__object': 0.3,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.315,
        'editprev__ai_edit': 0.25,
        'new__stock_on_board': 0.175,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.25,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.2,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a stranded 'the / a / this' is joined to its noun — e.g. 'the' + 'moun
    1006: {
        'new__stock': 0.5,
        'new__object': 0.2,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.45,
        'editprev__ai_edit': 0.03,
        'new__stock_on_board': 0.25,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.03,
        'editprev__hold': 0.08,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a 'the / a' is pulled back from the next line onto a wordy connector, 
    1007: {
        'new__stock': 0.35,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.315,
        'editprev__ai_edit': 0.15,
        'new__stock_on_board': 0.175,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.15,
        'editprev__hold': 0.35,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a line with nothing you could picture is folded into the line BEFORE i
    1008: {
        'new__stock': 0.3,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.25,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.25,
        'editprev__hold': 0.45,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
    # a line with nothing you could picture is folded into the line AFTER it
    1009: {
        'new__stock': 0.3,
        'new__object': 0.12,
        'new__wikipedia': 0.08,
        'new__map': 0.05,
        'new__typography': 0.01,
        'new__ai_stock': 0.27,
        'editprev__ai_edit': 0.25,
        'new__stock_on_board': 0.15,
        'new__wikipedia_on_board': 0.06,
        'editprev__add_stock': 0.03,
        'editprev__zoom': 0.25,
        'editprev__hold': 0.45,
        'editprev__draw': 0.04,
        'editprev__caption': 0.04,
    },
}

