"""
RULE_MEDIA_WEIGHTS.py  —  AUTO-GENERATED, but meant to be reviewed & edited
=========================================================================
For every tagged rule id the splitter can stamp on a line, this maps:

    <rule id> -> { 'description': <what the splitter spotted>,
                   'media_type_probabilities': { <media type>: affinity } }

The affinities are INDEPENDENT scores in [0,1] ('how well does this media
type suit a line the splitter cut for THIS reason'), NOT a distribution —
they do not sum to 1. SPLIT_AND_LABEL combines the per-rule affinities for
a line, applies the BIG GENERAL RULES (see SPLIT_AND_LABEL.py), then
normalises + samples to pick one media type.

Descriptions are mirrored from sentence_splitter.RULE_DESCRIPTIONS so you
can review the number -> meaning -> media-type linking in one place.
Regenerate with:  python3 gen_rule_media_weights.py > RULE_MEDIA_WEIGHTS.py
"""

RULE_MEDIA_WEIGHTS = {
    1: {
        "description": "the line ends with . ! ? ; or : — e.g. 'The dog jumped.' | 'The man ran.'",
        "media_type_probabilities": {
            'stock': 0.55,
            'object_generate': 0.2,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    2: {
        "description": "a dash breaks the line — e.g. 'it was huge —' | 'completely massive'",
        "media_type_probabilities": {
            'stock': 0.45,
            'object_generate': 0.25,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.15,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    3: {
        "description": "the line ends on a '...' or '…' — e.g. 'and then...' | 'silence'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.15,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.35,
            'static_of_previous': 0.3,
            'decorate_previous': 0.03,
        },
    },
    4: {
        "description": "the dramatic phrase right before a '...' gets its own line — e.g. 'the driest place on Earth' | '...'",
        "media_type_probabilities": {
            'stock': 0.35,
            'object_generate': 0.6,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.2,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    5: {
        "description": "a phrase in quotation marks gets its own line — e.g. she yelled | 'stop right there'",
        "media_type_probabilities": {
            'stock': 0.2,
            'object_generate': 0.12,
            'read_out': 0.7,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.15,
        },
    },
    6: {
        "description": "an aside in (brackets) gets its own line — e.g. 'the house' | '(built in 1920)' | 'was old'",
        "media_type_probabilities": {
            'stock': 0.25,
            'object_generate': 0.12,
            'read_out': 0.3,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.2,
            'decorate_previous': 0.4,
        },
    },
    7: {
        "description": "a scene-setting opener that ends in a comma — e.g. 'In the morning,' | 'we left'",
        "media_type_probabilities": {
            'stock': 0.4,
            'object_generate': 0.12,
            'read_out': 0.2,
            'wikipedia': 0.08,
            'map': 0.12,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.2,
            'decorate_previous': 0.03,
        },
    },
    8: {
        "description": "a comma that separates two clauses or list items — e.g. 'she ran,' | 'he walked'",
        "media_type_probabilities": {
            'stock': 0.55,
            'object_generate': 0.18,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    9: {
        "description": "a comma that introduces a 'who / which / that...' description — e.g. 'the dog,' | 'which was huge'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.12,
            'read_out': 0.1,
            'wikipedia': 0.22,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.5,
        },
    },
    10: {
        "description": "a joining word like 'when', 'because', 'which' or 'that' starts a new part — e.g. 'he left' | 'because it rained'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.12,
            'read_out': 0.4,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.3,
            'decorate_previous': 0.03,
        },
    },
    11: {
        "description": "a 'but' or 'or' after a long first part — e.g. 'we tried for hours' | 'but it failed'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.12,
            'read_out': 0.4,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.25,
            'decorate_previous': 0.03,
        },
    },
    12: {
        "description": "one complete action has finished and the next begins — e.g. 'the baker kneaded the bread' | 'while the fire crackled'",
        "media_type_probabilities": {
            'stock': 0.5,
            'object_generate': 0.25,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    13: {
        "description": "a very long wind-up finally reaches its main verb (a safety net for run-on sentences) — e.g. 'the tall man in the long red coat' | 'walked in'",
        "media_type_probabilities": {
            'stock': 0.35,
            'object_generate': 0.12,
            'read_out': 0.4,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.2,
            'decorate_previous': 0.03,
        },
    },
    14: {
        "description": "a long 'in / on / at / with...' phrase — e.g. 'she hid' | 'beneath the old wooden floor'",
        "media_type_probabilities": {
            'stock': 0.42,
            'object_generate': 0.12,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.12,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.18,
            'decorate_previous': 0.03,
        },
    },
    15: {
        "description": "a run of things listed with no verb between them — e.g. 'ribs,' | 'vertebrae,' | 'skulls'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.2,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.8,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    16: {
        "description": "another 'thing, the thing, the thing' list that the usual list-finder misses — e.g. 'the red car' | 'the blue truck'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.2,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.8,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    17: {
        "description": "a wrap-up word like 'all', 'both', 'each' or 'every' right after a list — e.g. 'cars, trucks, bikes' | 'all sped past'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.12,
            'read_out': 0.35,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.3,
            'decorate_previous': 0.03,
        },
    },
    18: {
        "description": "a name worth a dramatic reveal — a person, place, date or amount — e.g. 'a valley called' | 'Wadi Al-Hitan'",
        "media_type_probabilities": {
            'stock': 0.35,
            'object_generate': 0.35,
            'read_out': 0.1,
            'wikipedia': 0.65,
            'map': 0.3,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    19: {
        "description": "an amount of money gets its own line — e.g. 'it costs' | '$800,000'",
        "media_type_probabilities": {
            'stock': 0.4,
            'object_generate': 0.6,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    20: {
        "description": "a short command on its own — e.g. 'Stop.' | 'Look around.'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.2,
            'read_out': 0.5,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.15,
        },
    },
    21: {
        "description": "an 'and' or 'or' joining two complete sentences — e.g. 'she sang' | 'and he danced'",
        "media_type_probabilities": {
            'stock': 0.35,
            'object_generate': 0.12,
            'read_out': 0.35,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.2,
            'decorate_previous': 0.03,
        },
    },
    23: {
        "description": "a describing word revealed in the middle of a sentence — e.g. 'the water that was' | 'freezing cold'",
        "media_type_probabilities": {
            'stock': 0.28,
            'object_generate': 0.25,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.55,
        },
    },
    24: {
        "description": "a sentence ending on a number or amount — e.g. 'the whales vanished' | 'millions of years ago'",
        "media_type_probabilities": {
            'stock': 0.42,
            'object_generate': 0.35,
            'read_out': 0.1,
            'wikipedia': 0.12,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    25: {
        "description": "an extra comma-list pattern the basic comma rule misses — e.g. 'soaked,' | 'frozen,' | 'exhausted'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.2,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.72,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    26: {
        "description": "a long 'if / when / because...' opener that ends in a comma — e.g. 'if you already know the answer,' | 'you can skip ahead'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.12,
            'read_out': 0.42,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.3,
            'decorate_previous': 0.03,
        },
    },
    27: {
        "description": "a sentence ending on a pair of describing words — e.g. 'the place felt' | 'calm and alien'",
        "media_type_probabilities": {
            'stock': 0.28,
            'object_generate': 0.25,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.52,
        },
    },
    28: {
        "description": "a chunky 'of / in / with...' phrase stuffed with nouns and no verb — e.g. 'a tale' | 'of kings and battles'",
        "media_type_probabilities": {
            'stock': 0.4,
            'object_generate': 0.28,
            'read_out': 0.1,
            'wikipedia': 0.15,
            'map': 0.05,
            'joint_3_row': 0.3,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    29: {
        "description": "an '-ing' or '-ed' word that introduces what comes next — e.g. 'revealing' | 'a hidden cave'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.35,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.38,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    30: {
        "description": "after a place or name, the 'in / on / at...' that says WHERE splits off — e.g. 'Alvord Desert' | 'in Oregon'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.12,
            'read_out': 0.1,
            'wikipedia': 0.15,
            'map': 0.78,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    31: {
        "description": "a comma after a long, meaty clause — e.g. 'after searching the whole house for hours,' | 'they gave up'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.12,
            'read_out': 0.4,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.2,
            'decorate_previous': 0.03,
        },
    },
    32: {
        "description": "a 'to do something' inside a long sentence — e.g. 'they travelled for days' | 'to reach the coast'",
        "media_type_probabilities": {
            'stock': 0.42,
            'object_generate': 0.2,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.1,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    33: {
        "description": "a sentence ending on an 'of ...' phrase — e.g. 'one of the driest' | 'climates on Earth'",
        "media_type_probabilities": {
            'stock': 0.44,
            'object_generate': 0.3,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.1,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    34: {
        "description": "an 'is / was ...-ing' action in progress — e.g. 'the crowd was' | 'slowly gathering'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.2,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.32,
            'static_of_previous': 0.38,
            'decorate_previous': 0.03,
        },
    },
    35: {
        "description": "an 'is / looks / feels...' followed by the thing it describes — e.g. 'the sky is' | 'a deep burning red'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.3,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.48,
        },
    },
    36: {
        "description": "an 'it / them + -ing/-ed' description after a small word like 'of' — e.g. 'the feeling' | 'of being watched'",
        "media_type_probabilities": {
            'stock': 0.25,
            'object_generate': 0.12,
            'read_out': 0.42,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.3,
            'decorate_previous': 0.03,
        },
    },
    37: {
        "description": "a sentence ending on a describing word plus an 'in / on / for...' phrase — e.g. 'the road is straight' | 'for absurd distances'",
        "media_type_probabilities": {
            'stock': 0.38,
            'object_generate': 0.12,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.12,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.22,
        },
    },
    38: {
        "description": "a two-word verb (like 'set up', 'sped past') and the thing it acts on — e.g. 'they set up' | 'a huge tent'",
        "media_type_probabilities": {
            'stock': 0.4,
            'object_generate': 0.52,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    39: {
        "description": "the thing after a preposition gets its own line — e.g. 'shapes appeared' | 'in the rock'",
        "media_type_probabilities": {
            'stock': 0.42,
            'object_generate': 0.25,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.12,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    40: {
        "description": "a scene-change word like 'then', 'later' or 'suddenly' — e.g. 'they waited' | 'then everything changed'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.12,
            'read_out': 0.3,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.38,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.26,
            'decorate_previous': 0.03,
        },
    },
    41: {
        "description": "a joining word like 'as', 'while' or 'if' left hanging as a cliffhanger — e.g. 'it works' | 'because'",
        "media_type_probabilities": {
            'stock': 0.45,
            'object_generate': 0.12,
            'read_out': 0.5,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.22,
            'static_of_previous': 0.2,
            'decorate_previous': 0.03,
        },
    },
    42: {
        "description": "'X is / looks / becomes Y' — split to reveal the Y — e.g. 'the desert becomes' | 'a frozen wasteland'",
        "media_type_probabilities": {
            'stock': 0.4,
            'object_generate': 0.52,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.2,
        },
    },
    43: {
        "description": "'X has / owns / contains Y' — split to reveal the Y — e.g. 'the valley holds' | 'ancient whale bones'",
        "media_type_probabilities": {
            'stock': 0.35,
            'object_generate': 0.55,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.28,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    44: {
        "description": "'X made / built / created Y' — split to reveal the Y — e.g. 'the river carved' | 'a deep canyon'",
        "media_type_probabilities": {
            'stock': 0.4,
            'object_generate': 0.52,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.15,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    45: {
        "description": "'X saw / found / knew Y' — split to reveal the Y — e.g. 'scientists discovered' | 'fossil skeletons'",
        "media_type_probabilities": {
            'stock': 0.4,
            'object_generate': 0.52,
            'read_out': 0.1,
            'wikipedia': 0.18,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    46: {
        "description": "'X moves through / into / across Y' — split to reveal the place — e.g. 'water flowed' | 'across the plain'",
        "media_type_probabilities": {
            'stock': 0.35,
            'object_generate': 0.12,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.58,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.2,
            'decorate_previous': 0.03,
        },
    },
    47: {
        "description": "'so / such / more ... that / than ...' — split right before the payoff — e.g. 'so flat' | 'that satellites use it'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.25,
            'read_out': 0.42,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    48: {
        "description": "'X means / equals / stands for Y' — split to reveal the meaning — e.g. 'the name means' | 'Valley of the Whales'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.3,
            'read_out': 0.2,
            'wikipedia': 0.52,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    49: {
        "description": "an 'and' / 'or' sitting between two picture-able things — e.g. 'dunes' | 'and blistering heat'",
        "media_type_probabilities": {
            'stock': 0.35,
            'object_generate': 0.3,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.42,
            'manual_stock_add_to_previous': 0.26,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    50: {
        "description": "after a title-name like 'Alaric the Goth', split before the verb — e.g. 'Alaric the Goth' | 'invaded Rome'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.3,
            'read_out': 0.1,
            'wikipedia': 0.72,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    51: {
        "description": "the first item of a list gets its own line too — e.g. 'dunes,' | 'heat, and silence'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.2,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.72,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    52: {
        "description": "a sentence ending on a label that explains the thing just named — e.g. 'they found bones' | 'the remains of a whale'",
        "media_type_probabilities": {
            'stock': 0.35,
            'object_generate': 0.35,
            'read_out': 0.1,
            'wikipedia': 0.22,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.32,
        },
    },
    53: {
        "description": "a number or date right at the start of a sentence — e.g. 'In 1946,' | 'everything changed'",
        "media_type_probabilities": {
            'stock': 0.42,
            'object_generate': 0.25,
            'read_out': 0.2,
            'wikipedia': 0.08,
            'map': 0.15,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    54: {
        "description": "the sentence ends on a describing word or phrase that paints the picture — e.g. 'the water was' | 'freezing cold'",
        "media_type_probabilities": {
            'stock': 0.28,
            'object_generate': 0.25,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.52,
        },
    },
    55: {
        "description": "a roughly-this-much amount like 'nearly 500' or 'about two miles' — e.g. 'it stretched' | 'for nearly 100 miles'",
        "media_type_probabilities": {
            'stock': 0.44,
            'object_generate': 0.3,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.08,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    1000: {
        "description": "a tiny leftover bit (like 'and' or 'the') is attached to the line BEFORE it, where it belongs — e.g. 'the curious child' + 'and' → 'the curious child and'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.12,
            'read_out': 0.4,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.3,
            'decorate_previous': 0.03,
        },
    },
    1001: {
        "description": "a tiny leftover bit is attached to the line AFTER it, where it belongs — e.g. 'is' + 'big' → 'is big'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.12,
            'read_out': 0.4,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.3,
            'decorate_previous': 0.03,
        },
    },
    1002: {
        "description": "a lonely piece of punctuation ('...', a dash, a stray quote) is stuck back onto the nearest line — e.g. 'Yep.' + '...' → 'Yep....'",
        "media_type_probabilities": {
            'stock': 0.35,
            'object_generate': 0.12,
            'read_out': 0.3,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.25,
            'decorate_previous': 0.03,
        },
    },
    1003: {
        "description": "a lone noun is reunited with the 'that / which...' description that follows it — e.g. 'regions' + 'that are now dry' → 'regions that are now dry'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.12,
            'read_out': 0.3,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.35,
        },
    },
    1004: {
        "description": "a short scrap is joined back to the 'to / of / with...' word it completes — e.g. 'it costs about' + 'two dollars' → 'it costs about two dollars'",
        "media_type_probabilities": {
            'stock': 0.35,
            'object_generate': 0.12,
            'read_out': 0.35,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.25,
            'decorate_previous': 0.03,
        },
    },
    1005: {
        "description": "a lone '-ing / -ed' verb is reunited with the thing it acts on — e.g. 'revealing' + 'evidence' → 'revealing evidence'",
        "media_type_probabilities": {
            'stock': 0.35,
            'object_generate': 0.3,
            'read_out': 0.2,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.25,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    1006: {
        "description": "a stranded 'the / a / this' is joined to its noun — e.g. 'the' + 'mountain' → 'the mountain'",
        "media_type_probabilities": {
            'stock': 0.5,
            'object_generate': 0.2,
            'read_out': 0.1,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.04,
            'decorate_previous': 0.03,
        },
    },
    1007: {
        "description": "a 'the / a' is pulled back from the next line onto a wordy connector, so the next line can start on a real word — e.g. 'but what if' + 'the' (from 'the planet') → 'but what if the' | 'planet'",
        "media_type_probabilities": {
            'stock': 0.35,
            'object_generate': 0.12,
            'read_out': 0.35,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.2,
            'decorate_previous': 0.03,
        },
    },
    1008: {
        "description": "a line with nothing you could picture is folded into the line BEFORE it — e.g. 'dogs run' + 'but' → 'dogs run but'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.12,
            'read_out': 0.45,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.35,
            'decorate_previous': 0.03,
        },
    },
    1009: {
        "description": "a line with nothing you could picture is folded into the line AFTER it — e.g. 'but' + 'the dog runs' → 'but the dog runs'",
        "media_type_probabilities": {
            'stock': 0.3,
            'object_generate': 0.12,
            'read_out': 0.45,
            'wikipedia': 0.08,
            'map': 0.05,
            'joint_3_row': 0.05,
            'manual_stock_add_to_previous': 0.03,
            'zoom_prev_img': 0.03,
            'static_of_previous': 0.35,
            'decorate_previous': 0.03,
        },
    },
}

